---
- name: Make sure file is in place
  file: path=/vol/jenkins_home owner=1000 state=directory
  sudo: yes

- name: Ensure Jenkins is up
  docker: image="ci:5000/jenkins" volumes=/vol/jenkins_home:/var/jenkins_home name=jenkins ports=8080:8080,50000:50000 
